sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - node
cache:
  yarn: true
notifications:
  email: false
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/lokesh-coder/filament.git
  - git checkout master
  - git config push.default current
after_success:
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    npm run release  || exit 1
    npm run release-log  || exit 1
  fi
branches:
  only:
    - master
deploy:
  provider: npm
  email: mexican.dirtyfellow@gmail.com
  api_key: 
    secure: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: lokesh-coder/filament
