sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - node
cache:
  yarn: true
notifications:
  email: false
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/lokesh-coder/filament.git
after_success:
  - git checkout master
  - git config push.default current
  - npm run release
  - npm publish --access=public
  - npm run release-log